<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Sia.NET\Sia\Sia.csproj" />
    <ProjectReference Include="..\..\Sia.NET\Sia.CodeGenerators\Sia.CodeGenerators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\Sia.Math\Sia.Math\Sia.Math.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Sia.Math" />
  </ItemGroup>

</Project>
